version: '3.7'

services:
  app:
    build:
      context: .
    ports:
    - 9001:9001
    environment:
      - PORT=9001
    depends_on:
      - swagger
  swagger:
      image: swaggerapi/swagger-ui
      ports:
        - 9002:8080
      environment:
        - SWAGGER_JSON=/swagger/api.yml
      volumes:
      - type: bind
        source: ./api.yml
        target: /swagger/api.yml